# -*- coding: utf-8 -*-
"""08OCT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W45j61de6UCfjc1tcVvqhAjZnJIb40Ko
"""
import threading
from fyers_apiv3 import fyersModel
from indicators import alligator, vroc, sma
import pandas as pd
import numpy as np
import time
client_id = "ZHQ4IJL7TI-100"
with open("access_token", "r") as f:
    access_token = f.read()

fyers = fyersModel.FyersModel(client_id=client_id, is_async=False, token=access_token, log_path="")

data = {
    "symbol": "NSE:ZEEL-EQ",
    "resolution": "1",
    "date_format": "1",
    "range_from": "2024-07-01",
    "range_to": "2024-10-07",
    "cont_flag": "1"
}

response = fyers.history(data=data)
len(response['candles']), response

# with open("data/zeel/NSE:ZEEL-EQ", 'w') as file:
#     file.write("Open,High,Low,Close,Volume")
#
#     for i in response['candles']:
#         file.write(f"\n{i[1]},{i[2]},{i[3]},{i[4]},{i[5]}")

temp = []
for c in response['candles']:
    temp.append(sum(c[2:4])/2)

alli = alligator(pd.Series(temp))
alli = alli.to_numpy()
alli

dates = []
X = []
k = 0
# for i in range(len(response['candles'])-1):
for i in range(10):
    candle = response["candles"][i]
    d = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(candle[0]))
    if d not in dates:
        dates.append(d)
        temp = []
        temp.append(d)
        temp.append(candle[1])
        temp.append(candle[2])
        temp.append(candle[3])
        temp.append(candle[4])
        temp.append(round(alli[i][0], 2))
        temp.append(round(alli[i][1], 2))
        temp.append(round(alli[i][2], 2))
        temp.append(round(sma(np.array(response['candles'])[:i+1, 4], 5)[-1], 2))
        temp.append(round(sma(np.array(response['candles'])[:i+1, 4], 15)[-1], 2))
        temp.append(candle[5])
        temp.append(round(vroc(np.array(response['candles'])[:i+1, 5], 14), 2))
        X.append(temp)
        print("id:", i, "\tdata:", temp)
    else:
        k += 1
        print("skipping", k, "\t", d)


with open("abc.csv", 'w') as f:
    f.write("DATE," + "OPEN," + "HIGH," + "LOW," + "CLOSE," + "JAW," + "TEETH," + "LIPS," + "MA5," + "MA15," + "VOLUME,"
            + "VROC")
    for x in X:
        f.write("\n" + str(x)[1:-1])

